general:
  
  # Thrall spawn name.
  spawn-name: Thrall                        
  
  # Initial health when the Thrall is spawned. (integer)
  initial-health: 20                        
  
  # Maximum health the Thrall can get when being healed. (integer)
  max-health: 30                            
  
  # Enemy detection range for Thralls when they are in Aggressive mode.
  detection-range: 10.0                     
  
  # Multiply the enemy detection range by this amount when the Thrall has a ranegd weapon.
  ranged-detection-multiplier: 1.5          
  
  # Multiply the base Entity speed when Thralls are running, affects Follow and Idle movement.
  run-speed-multiplier: 1.5                 
  
  # Thralls that haven't been commanded by this period of time are removed from the selection. (seconds)
  selection-release-cooldown: 20            
  
  # Maximum distance in blocks for Thralls in Idle to wander before they return to their starting point.
  idle-wander-max-distance: 4               
  
  # Distance at when following Thralls should stop, for Thralls in Idle, this represent the distance to the player to stop wandering.
  follow-min-distance: 3                    
  
  # Thralls that are further than this distance are teleported to their owner. For Idle, this marks when they start to run.
  follow-max-distance: 20                   
  
  # Time for aggressive Thralls to forget their target if they are not in range. It affects Thralls healing as well.
  attack-demiss-cooldown: 30                

  # Accuracy for arrows shot by Thralls as a number between 0 (blind) to 1 (sharpshooter), set to -1 to use Vanilla settings.
  ranged-accuracy: 0.75
  
  # Arrow launch speed in blocks per tick (Player max bow speed is 3)
  # Ignored if "ranged-accuracy" is set to -1 (Vanilla)
  arrow-speed: 3

  # Chance for a Thrall to block an incoming attack when a shield is equipped
  shield-block-chance: 0.5

  # Maximum amplitue for a random distance (in blocks) selection offset used to avoid many Thralls targetting the same entity at once.
  selection-bias: 4


# Thrall Behavior names and States, State names should be typed taking "aggression-state-message" into consideration. Behavior names should be in present continous.
states:
  # Message sent to the owner when the Aggression mode changes. The two placeholders %s are 1) Name of the Thrall, 2) Aggression mode.
  behavior-state-message: "%s is now %s"  
  
  # Message sent when the mode changes for many Thralls (e.g. Horn commands). The two placeholders %d %s are 1) Number of Thralls, 2) Aggression mode.
  horn-command-message: "Changing %d Thralls to %s" 

  idle: "Guarding"
  follow: "Following"
  attack: "Attacking"
  heal: "Healing"
  idle-verb: "idle"
  follow-verb: "following you"
  defend-verb: "defending you"
  aggressive-verb: "aggresive"


# Thrall regeneration ritual settings that controls the amount of potions to be used and the effects that will play each time a potion is applied.
ritual-action:
  
  # Number of potions used to convert a Zombified Piglin into a Thrall
  potion-count: 4                     
  
  # Type of potion effect, see PotionEffectType class.
  potion-type: WEAKNESS               
  
  # List with the Particle class effect to spawn when the Thrall is being converted
  particles:                          
    FLAME:
      count: 80
      speed: 0.01
      box-size: [0.1, 0.2, 0.1]
    ENCHANT:
      count: 60
      speed: 0.02
      box-size: [1.5, 1.5, 1.5]
  
  # Sound to play when the Zombified Piglin is hit by a potion
  sound:                              
    type: ENTITY_ZOMBIFIED_PIGLIN_ANGRY
    volume: 1.0
    pitch: 1.0


# Effects that play when a Thrall is spawned or converted
thrall-spawn:
  
  # Message to send to the owner when the Thrall spawns, the placeholder %s represents the name of the Thrall
  message: "Your Thrall rises!"        
  
  # List with the Particle class effect to spawn when the Thrall is spawned
  particles:                          
    SOUL:
      count: 40
      speed: 0.02
      box-size: [1, 1, 1]
    FLAME:
      count: 80
      speed: 0.05
      box-size: [0.1, 0.2, 0.1]
  
  # Sound to play when the Thrall spawns
  sound:                              
    type: ENTITY_DONKEY_DEATH
    volume: 1.0
    pitch: 0.5

thrall-death:
  
  #  Message to be send to the owner when a Thrall is killed, the placeholder %s represents the name of the Thrall
  message: "%s has fallen."          
  
  # List with the Particle class effect to spawn when the Thrall is killed
  particles:                          
    SOUL:
      count: 20
      speed: 0.02
      box-size: [1, 1, 1]
      
  
  # Sound to play when the Thrall dies
  sound:                              
    type: ENTITY_DONKEY_DEATH
    volume: 1.0
    pitch: 0.5

# Settings regarding the Target score system used by thralls to determine whcih enemy should attack first
# The score is a linear sum of the values described below. negative values are subtracted from the score.
# Enemies with lower score are more likely to be targeted by the thrall.
scores:
  # Enemies with a score greater than this value are ignored by the Thrall
  score-threshold: 15

  # Is the targeted entity a player?. By default this is -5 which gives priority to player entities.
  is-player: -5

  # Is the targeted entity a mob?. By default this value is +2 which reduces priority to mobs. 
  is-mob: 2

  # Penalization if the entity is farther than detection-range. By default the value is +5
  is-far: 5

  # Penalization if the entity is not directly visible to the Thrall. By default the value is +10
  is-visible: 10

  # Score added if the entity is close to the owner, the limit is defined as 2 x follow-min-distance.
  # By default, the value is -5, which gives priority to entities closer to the player.
  player-danger: -5

  # Extra score added for every (health / health-divisor) points of the entity.
  # By default the value is -10, which prioritizes entities with higher hp
  health-divisor: -10


misc:
  debug-mode: false